### ISSUE TITLE
SQLite build at Yggdrasil

### ISSUE THREAD

**Issue by visr** [JuliaDatabases/SQLiteBuilder#2]
FYI, since I need SQLite as a dependency, and wanted to make use of the 1.3 Artifacts system for that. So I went ahead and added SQLite to Yggdrasil at https://github.com/JuliaPackaging/Yggdrasil/pull/144.

This resulted in https://github.com/JuliaBinaryWrappers/SQLite_jll.jl.

The build is based on this repository, I only bumped the SQLite version to 3.30.1.

For pre 1.3 use it should be possible to also create a build.jl file using https://github.com/JuliaPackaging/Yggdrasil/blob/master/generate_buildjl.jl, but for my own use I think I'll just require 1.3. (I'm not using SQLite.jl directly).

**Comment by visr** [comment]
Closing this since SQLite.jl is using the Yggdrasil build as well now, see https://github.com/JuliaDatabases/SQLite.jl/pull/201.

**Comment by quinnj** [comment]
I'm going to officially archive this repo
